### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Plainbroke** [sdetweil/MagicMirror-backup-restore#10]
I used to be able to run locally,  but now I can not remember how I did it.  
The backup from this site does not work for me.  Used to be simpler.  I downloaded the zip file and put the backup and restore sh files in home/pi but do not know what to do from there.

**Comment by sdetweil** [comment]
what do you mean it doesn't work by copy/paste the command and add your parms  if any

**Comment by sdetweil** [comment]
i see they didn't work with no parms.. I have fixed that

**Comment by sdetweil** [comment]
IF you want them locally,. which I suggest against , as I change them 
just git clone the repo and then run them from there they are executable commands
```sh
~/MagicMirror_backup_restore/mm_backup.sh ...... whatever parms needed
```

**Comment by sdetweil** [comment]
did you solve this?

**Comment by sdetweil** [comment]
@Plainbroke
