### ISSUE TITLE
Restore not working. Message "restoring MM configuration from /home/pi/MM_backup to /home/pi/MagicMirror" but nothing else happens.

### ISSUE THREAD

**Issue by lxne** [sdetweil/MagicMirror-backup-restore#11]
Hello,

I am just trying to restore a backup, but it won't work.
- Raspberry Pi 4
- fresh Bookworm 64bit
- fresh MM 2.27.0 installation

Now when I do `bash -c "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror-backup-restore/main/mm_restore.sh)" -s /home/pi/MagicMirror -b /home/pi/MM_backup`
I get the message…
> restoring MM configuration from /home/pi/MM_backup to /home/pi/MagicMirror

but nothing else happens.

The backup process seems to have worked fine.
The backup folder contains…
- config.js
- custom.css
- MMM-GoogleAssistant (folder with credentials and token)
- module_list

Am I missing anything?

**Comment by sdetweil** [comment]
oops, sorry, left 'exit' in code after testing.. 

try again

**Comment by lxne** [comment]
Ah, wonderful. It's processing.
