### ISSUE TITLE
Backup not working as expected. xargs: invalid option -- 'J'

### ISSUE THREAD

**Issue by lxne** [sdetweil/MagicMirror-backup-restore#12]
Hi, this used to work, but right now, when I try…
`bash -c "$(curl -sL https://raw.githubusercontent.com/sdetweil/MagicMirror-backup-restore/main/mm_backup.sh)"`

I get…
> updating folder /home/pi/MM_backup
> xargs: invalid option -- 'J'
> Try 'xargs --help' for more information.
> On branch main
> nothing to commit, working tree clean
> backup completed, see the git repo at /home/pi/MM_backup
> see this link for how to fetch tags for restore
> https://devconnected.com/how-to-list-git-tags/
> or run the list_tags.sh command from this repo

and in the MM_backup folder I only have two files.
config.js and custom.css
GA folder and module list are missing.

Any idea what the isue could be?

**Comment by sdetweil** [comment]
try again, fixed.. sorry
