### ISSUE TITLE
no user name or email set, required to save changes to git, please see the -u and -e parameters

### ISSUE THREAD

**Issue by Dogweazle** [sdetweil/MagicMirror-backup-restore#5]
Even if I'm setting git parameters like:

git config --global user.email "xyz@xyz"
git config --global user.name "xyz"

I still get the failure message:

no user name or email set, required to save changes to git, please see the -u and -e parameters

if I'm starting backup script with:
./mm_backup.sh

**Comment by sdetweil** [comment]
ok. can. u run like this and post the output or send to my email?  same userid at gmail

bash -x ./mm_backup.sh 2>xxx.txt

xxx.txt is the output

also, you don't have to download the script to run it

**Comment by sdetweil** [comment]
i see that the parameters are not handled correctly..

try the withfiles branch

**Comment by sdetweil** [comment]
fixed in main branch
